[config]
default_task = "build-release"

[tasks.build]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown"]

[tasks.build-release]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]
